name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'
      - name: release
        run: |
          npm ci
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run ci:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
